/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PPL;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sompod_Programmer
 */
public class FemaleUser extends javax.swing.JFrame {

    /**
     * Creates new form MaleUser
     */
    void showwarning_masg() {
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int choose = JOptionPane.showConfirmDialog(null,
                        "Have you save the file?\nDo you really want to exit the application ?",
                        "Confirm Close", JOptionPane.YES_NO_OPTION,
                        JOptionPane.INFORMATION_MESSAGE);
                if (choose == JOptionPane.YES_OPTION) {

                    e.getWindow().dispose();
                    System.exit(0);

                } else {
                    // System.out.println("do nothing");
                }
            }
        });
    }

    public FemaleUser() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        showwarning_masg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"PLAY WITH LEARNING\"  Developed by sompod.");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Do you read the text book reading to boring?");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(590, 180, 260, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 0));
        jLabel11.setText("Hey Dear...");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(640, 150, 160, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Let's learn another way.");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(610, 200, 230, 22);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thinking cloud1.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(570, 120, 330, 170);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 490, 140, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dad.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 130, 110, 120);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brotherbutton.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 250, 140, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mom.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 120, 110, 130);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grandmabutton.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(400, 440, 140, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sis.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 310, 110, 130);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mombutton.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(220, 250, 140, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grandpa.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 310, 110, 130);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grandpabutton.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(220, 440, 140, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grandma.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(410, 310, 110, 130);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sisbutton.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(60, 440, 140, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brother.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(400, 130, 110, 120);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dadbutton.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(60, 250, 140, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/female_book.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(720, 200, 210, 350);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userbackground.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 990, 580);

        setSize(new java.awt.Dimension(953, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
                 this.setVisible(false);
        new DadTask().setVisible(true);
        DadTask.check = 2;
        DadTask.jLabel4.setText(jLabel11.getText());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainInterface s = new MainInterface();
        s.setVisible(true);
        s.jLabel2.setText("WELCOME TO");
        s.jLabel4.setText("\"PLAY WITH LEARNING\"");
        s.jLabel5.setText(" APPLICATION.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MomTask().setVisible(true);
        MomTask.check = 2;
        MomTask.jLabel4.setText(jLabel11.getText());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
                 this.setVisible(false);
        new SisTask().setVisible(true);
        SisTask.check = 2;
        SisTask.jLabel4.setText(jLabel11.getText());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                 this.setVisible(false);
        new BroTask().setVisible(true);
        BroTask.check = 2;
        BroTask.jLabel4.setText(jLabel11.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                 this.setVisible(false);
        new grandmotherTask().setVisible(true);
        grandmotherTask.check = 2;
        grandmotherTask.jLabel4.setText(jLabel11.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
                 this.setVisible(false);
        new grandfatherTask().setVisible(true);
        grandfatherTask.check = 2;
        grandfatherTask.jLabel4.setText(jLabel11.getText());
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FemaleUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FemaleUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FemaleUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FemaleUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FemaleUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
