/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PPL;

import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author Sompod_Programmer
 */
public class grandmotherTask extends javax.swing.JFrame {

    /**
     * Creates new form MomTask
     */
    public Preferences prefs = Preferences.userNodeForPackage(PPL.UserData.class);
    public static int check = 0;

    public grandmotherTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(649, 393, 130, 30);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backarrow.png"))); // NOI18N
        getContentPane().add(jButton9);
        jButton9.setBounds(740, 240, 50, 60);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/levelLookbutton.png"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 180, 90, 80);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/levelLookbutton.png"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 180, 90, 80);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/levelLookbutton.png"))); // NOI18N
        getContentPane().add(jButton3);
        jButton3.setBounds(610, 180, 90, 80);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/levelLookbutton.png"))); // NOI18N
        getContentPane().add(jButton4);
        jButton4.setBounds(250, 290, 90, 80);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/levelLookbutton.png"))); // NOI18N
        getContentPane().add(jButton5);
        jButton5.setBounds(370, 290, 90, 80);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/levelLookbutton.png"))); // NOI18N
        getContentPane().add(jButton6);
        jButton6.setBounds(490, 290, 90, 80);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/levelLookbutton.png"))); // NOI18N
        getContentPane().add(jButton7);
        jButton7.setBounds(610, 290, 90, 80);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/levelbutton1.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(250, 180, 90, 80);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Hey \"null\"");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 10, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Let's try to know...");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 60, 250, 15);

        jLabel2.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("What you know about your grandma?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 40, 340, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playingbackground.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 430);

        setSize(new java.awt.Dimension(793, 428));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if (check == 1) {
            this.setVisible(false);
            new MaleUser().setVisible(true);
            MaleUser.jLabel11.setText(prefs.get("user_name", "som"));
        } else if (check == 2) {
            this.setVisible(false);
            new FemaleUser().setVisible(true);
            FemaleUser.jLabel11.setText(prefs.get("user_name", "som"));
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Next update.");
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grandmotherTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grandmotherTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grandmotherTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grandmotherTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grandmotherTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
